name: Feature mode
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to run the tests: dev / stage / prod'
        required: true
        default: 'stage'
      browser:
        description: 'Select the  browser to run the tests: chrome / firefox'
        required: true
        default: 'chrome'
      specs:
        description: 'Add the spec file path that you want to run:'
        default: 'cypress/e2e/*.spec.ts'
        required: true
jobs:
  feature-job:
    name: Running tests on feature mode
    # Setting the OS to run the cypress tests
    runs-on: ubuntu-latest
    timeout-minutes: 1
    # Setting the Docker container
    #container:
    # image: cypress/included:12.3.0
    #
    steps:
      #
      - name: Checkout
        uses: actions/checkout@v3
      #
      - name: Get current date
        id: date
        run: |
          echo "date=$(date +'%Y-%m-%d %H-%M')" >> $GITHUB_OUTPUT

      # - name: Conditional to run on STAGE - Copy data from Secrets to cypress.${{github.event.inputs.environment}}.json
      #   if: github.event.inputs.environment == 'stage'
      #   run: |
      #     echo '${{ secrets.CYPRESS_ENV_STAGE }}' > env/cypress.${{github.event.inputs.environment}}.json

      # - name: Conditional to run on PROD - Copy data from Secrets to cypress.env.json
      #   if: github.event.inputs.environment == 'prod'
      #   run:
      #     echo "RUNNING PROD"

      - name: Cypress run 🧪
        uses: cypress-io/github-action@v5
        with:
          command: npx cypress run --browser ${{github.event.inputs.browser}} --env configFile=${{github.event.inputs.environment}} --spec ${{github.event.inputs.specs}}
      #
      - name: Create Test Summary
        id: test_summary
        uses: test-summary/action@v2.1
        if: always()
        with:
          paths: cypress/reports/junit/**/*.xml
          output: cypress/reports/results.html
      #
      - name: Upload test summary
        uses: actions/upload-artifact@v3
        with:
          name: test-summary
          path: cypress/reports/results.html

      - name: Adding markdown
        run: |
          echo "### Hello world! :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.test_summary.outputs.passed }}"
          echo "This is the lead in sentence for the list" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          echo "- Lets add a bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- Lets add a second bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- How about a third one?" >> $GITHUB_STEP_SUMMARY
