name: Feature mode
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to run the tests: dev / stage / prod'
        required: true
        default: 'stage'
      browser:
        description: 'Select the  browser to run the tests: chrome / firefox'
        required: true
        default: 'chrome'
      specs:
        description: 'Add the spec that you want to run:'
        required: true  
jobs:
  feature-job:
    name: Running tests on feature mode
    # Setting the OS to run the cypress tests
    runs-on: ubuntu-latest
    # Setting the Docker container
    #container: 
      #image: cypress/browsers:node18.6.0-chrome105-ff104
    #
    steps:
      #
      - name: Checkout
        uses: actions/checkout@v3
      #  
      - name: Conditional to run on STAGE - Copy data from Secrets to cypress.${{github.event.inputs.environment}}.json
        if: github.event.inputs.environment == 'stage'
        run: |
          echo '${{ secrets.CYPRESS_ENV_STAGE }}' > env/cypress.${{github.event.inputs.environment}}.json
  
      - name: Conditional to run on PROD - Copy data from Secrets to cypress.env.json 
        if: github.event.inputs.environment == 'prod'
        run: 
          echo "RUNNING PROD"
          
      - name: Git ID
        if: always()
        run: | 
          echo 'JOB LINK: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
          'JOB NAME: ${{ github.run_name }}
          'NAME: ${{ inputs.run_name }}
          'JOB: ${{ github.action.name }}
          'BRANCH NAME: ${{ github.ref_name }}
          'JOB STATUS: ${{ job.status }}
          'JOB ENV: ${{github.event.inputs.environment}}
          'RUNNER NAME': ${{ runner.name }}
          
          
        
        
      #- name: Cypress run 
        #uses: cypress-io/github-action@v5
        #with:
         # command: npx cypress run --browser ${{github.event.inputs.browser}} --env configFile=${{github.event.inputs.environment}} --spec ${{github.event.inputs.specs}}
      #
  
      # Slack channel id, channel name, or user id to post message.
      # See also: https://api.slack.com/methods/chat.postMessage#channels
      # You can pass in multiple channels to post to by providing a comma-delimited list of channel IDs.
      # C04J1G54BPU - Cypress Notification channel
      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: 'C04J1G54BPU'
          payload: |
           {
            "blocks": [
              { "type": "divider" },
              {
                "type": "image",
                "title": {
                  "type": "plain_text",
                  "text": "Testing Slack",
                  "emoji": true
                },
                "image_url": "https://yt3.ggpht.com/iD0oePTGV8tZwEEP_WEG2rvyNiQAVfmjhawFMCj17ARjjmw-J70k9NDjSE5QTzD9Vk3ayBU=s900-c-k-c0x00ffffff-no-rj",
                "alt_text": "marg"
              },
              {
                "type": "actions",
                "elements": [
                  {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": FEATURE_MODE
                    },
                    "url": https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
                  }
                ]
              }
            ],
           } 
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          
      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      #   
      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
          allure_report: allure-report
          keep_reports: 20
          gh_pages: allure
       #   
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
