name: E2E Cypress tests

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to run the tests: dev / stg / prod'
        required: true
        default: 'stg'
      browser:
        description: 'Select the  browser to run the tests: chrome / electron'
        required: true
        default: 'chrome'
      tag:
        description: 'Test scenario tags: @regressivo / @smoke / @login'
        required: false
        default: '@regressivo'
  schedule:
    - cron: "0 0 * * *"
    
env:
  DEFAULT_ENV: "stg"
  DEFAULT_BROWSER: "chrome"
  DEFAULT_TAG: "@regressivo"

jobs:
  UI_test:
    name: Run all e2e tests 
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.16.0-chrome90-ff88
    steps:
      #
      - name: Checkout
        uses: actions/checkout@v3
      # 
      - name: Copying data to cypress.env.json
        run: cp env/cypress.${{github.event.inputs.environment || env.DEFAULT_ENV}}.json cypress.env.json
        shell: bash
      #
      - name: Cypress run 
        uses: cypress-io/github-action@v2
        with:
          command: npx cypress run --browser ${{github.event.inputs.browser || env.DEFAULT_BROWSER}} --env configFile=${{github.event.inputs.environment || env.DEFAULT_ENV}} allure=true
      #
      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      #   
      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 20
          # gh_pages: allure
       #   
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
    


